name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            set -e
            if [ ! -d ~/url-shortener ]; then
              git clone https://github.com/${{ github.repository }} ~/url-shortener
            fi
            cd ~/url-shortener
            git fetch origin main && git reset --hard origin/main
            sudo docker build -t url-shortener:latest .
            sudo docker rm -f url-shortener || true
            sudo docker run -d --name url-shortener -p 80:80 --env-file .env url-shortener:latest
